---
version: '3'

services:
  drupal:
    build: ./
    image: ackama/drupal-phpunit-test:latest
    container_name: drupal
    environment:
      DRUPAL_DATABASE_HOST: drupal-mysql
      DRUPAL_DATABASE_PORT: 3306
      DRUPAL_DATABASE_NAME: drupal
      DRUPAL_DATABASE_USERNAME: drupal
      DRUPAL_DATABASE_PASSWORD: drupal
      DRUPAL_DOWNLOAD_VERIFY_CERT: 'FALSE'
      DRUPAL_DOWNLOAD_IF_NOT_PRESENT: 'FALSE'
      DRUPAL_RUN_COMPOSER_INSTALL: 'FALSE'
      # Generate a salt with: `php -r "echo bin2hex(random_bytes(25));"`
      DRUPAL_HASH_SALT: db0de8a1556aa5348f87cfc950cd2c9641713d46e9412c8b05
    ports:
      - '8080:80'
    restart: always
  mysql:
    image: mysql:5.7
    container_name: drupal-mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    ports:
      - '3306:3306'
